// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNopwBi4Q2L9cC_0ExSZU0BHtpK28r3BA',
    appId: '1:258964973797:android:c2b4401c44158607464c0c',
    messagingSenderId: '258964973797',
    projectId: 'todolist-lumc',
    storageBucket: 'todolist-lumc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-QQXjgWgrQFlD-Zx3K_u-brijWZsYwwY',
    appId: '1:258964973797:ios:f21db34fad3962cf464c0c',
    messagingSenderId: '258964973797',
    projectId: 'todolist-lumc',
    storageBucket: 'todolist-lumc.appspot.com',
    androidClientId: '258964973797-muho95hso9mhecmm96dic3imrn9kq07c.apps.googleusercontent.com',
    iosClientId: '258964973797-4id1nbog1q3g0dl9io5dhkbm7ikmon5i.apps.googleusercontent.com',
    iosBundleId: 'br.com.lucianamcedro.todolistProvider',
  );
}
